server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
    url: jdbc:postgresql://localhost:5432/LearningDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

