server:
  port: 8081

spring:
  application:
    name: fraud

  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/LearningDB
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

  zipkin:
    base-url: http://192.168.99.100:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
